application:
  title: "Spring Cloud Function Demo"
  version: @project.version@

spring:
  application:
    name: ${application.title}
  profiles:
    active: dev
  cloud:
    function:
      definition: findMovie|findSong
logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.boot: warn
    com.kapresoft.demo: debug