application:
  title: "Spring Cloud Function Demo"
  version: @project.version@

spring:
  application:
    name: ${application.title}
  profiles:
    active: dev
  cloud:
    function:
      #definition: reverse|uppercase
      #definition: findSong
      #definition: findMovie
      definition: customRouter
logging:
  level:
    root: warn
    org.springframework: warn
    org.springframework.boot: warn
    com.kapresoft.demo: debug